version: "3.7"

services:
  app:
    command: yarn start
    depends_on:
      - mongodb
    image: node:12.10.0
    ports:
      - 3000:3000
    volumes:
      - ../../../../repositories/backend/nodejs:/workspace
    working_dir: /workspace

  mongodb:
    image: mongo:3.4.23
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo:/data/db

volumes:
  mongo:
